### ISSUE TITLE
Extension blanks out login page

### ISSUE THREAD

**Issue by gerv** [Osmose/mailman-admin-helper#1]
The lists I moderate, at least, have a password I have to enter before seeing the admin interface. This is the same URL as the admin interface itself. Your script appears to hide the password field and login button, making it impossible to login.

Now what would be awesome is if you clicked it automatically (the browser auto-fills the password). But just hiding it makes it impossible to log in!

**Comment by Osmose** [comment]
Phew. It took 5 tags, but I finally got CircleCI set up to auto-build a signed add-on when I push tags, and this is out as [v0.1.5](https://github.com/Osmose/mailman-admin-helper/releases/tag/v0.1.5).
